### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by luckenzo** [fmind/euphony#1]
I am trying to use euphony to get the families of some malware samples from the VT report. The VT report is a json file with each sample on a single line like this: `{"AegisLab":"Android.C2P.Kh!c","name":"VirusShare_262cd01856fb7bcc3e4256c41faaa7c6.apk","CAT-QuickHeal":"Android.Yekrand.Ade26 (AdWare)"}`
and I execute euphony using: `java -jar euphony.jar -r vtReport.json` and encounter the following exception which I have not been able to resolve. `Exception in thread "main" java.lang.AssertionError: Assert failed: (not-empty labels)
	at euphony.tasks$with_parse_mapping_BANG_.invokeStatic(tasks.clj:53)
	at euphony.tasks$with_parse_mapping_BANG_.invoke(tasks.clj:53)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at euphony.tasks$make_BANG_.invokeStatic(tasks.clj:235)
	at euphony.tasks$make_BANG_.invoke(tasks.clj:233)
	at euphony.core$_main.invokeStatic(core.clj:57)
	at euphony.core$_main.doInvoke(core.clj:51)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at euphony.core.main(Unknown Source)`
Any idea how to resolve this please?

**Comment by fmind** [comment]
Each line in the JSON file must correspond to the original VT report. This is required to retrieve some meta data like the number of positive detections or the identifier (sha256) of each malware.

If you have access to the original reports, you can simply concatenate them to create the input file.

If not, you have to recreate this structure. At least, each line must contain the following keys: `scan_id, scan_date, resource, positives and scans`.

The structure you described corresponds to the value associated to the scans key. Note that this structure should be adapted to VT format, with at least the `result` and `detected` keys:
```
"AVware": {"result": "Trojan.AndroidOS.Generic.A", "detected": true}
```

**Comment by luckenzo** [comment]
Thank you for the response. I don't have the original report as I stripped out those info and only wrote to file the ones I wanted. I will have to query VT again as I suppose I cannot use forged values for the keys you highlighted. I will close the issue afterwards or post any further issues.

**Comment by fmind** [comment]
You can use forged values if it's more convenient for your use case.

Out of the keys I highlighted, only `resource, positives, scans` must be valid. The `resource` key is the sha256 of the application. If you have them, you can compute the value from your shell. The `scan_id` and `scan_date` keys can be faked as long as their format are valid.

These values are meant to be used in a context where Euphony findings are persistent (with --database-url). In this case, Euphony learns some associations (e.g. conficker = malware name), and use them in your next run. Otherwise, they are discarded after each execution.

If you get some assertion error, you can have a look in src/euphony/commands/importer.clj:report>struct->datoms

**Comment by luckenzo** [comment]
Looking at the report from VT, some keys you require are missing (see below). What do I do?
`b'{"report": ["2017-07-19 22:43:36", {"Bkav": "", "TotalDefense": "", "MicroWorld-eScan": "", "nProtect": "", "CMC": "", "CAT-QuickHeal": "Android.Hiddad.GEN12762", "McAfee": "Artemis!252D0772788D", "Malwarebytes": "", "Zillya": "", "SUPERAntiSpyware": "", "TheHacker": "", "Alibaba": "A.H.Rog.HiddenApp", "K7GW": "Trojan ( 004f45e81 )", "K7AntiVirus": "", "Arcabit": "Android.Trojan.HiddenAds.QF", "Baidu": "", "F-Prot": "", "SymantecMobileInsight": "Trojan:Malapp", "Symantec": "Trojan.Gen.2", "ESET-NOD32": "a variant of Android/TrojanDropper.Agent.AAE", "TrendMicro-HouseCall": "ANDROIDOS_ZTORG.OPSUA", "Avast": "", "ClamAV": "", "Kaspersky": "HEUR:Trojan-Downloader.AndroidOS.Rootnik.g", "BitDefender": "Android.Trojan.HiddenAds.QF", "NANO-Antivirus": "Trojan.Android.Agent.ejanrs", "ViRobot": "", "Tencent": "a.gray.generic", "Ad-Aware": "", "Trustlook": "Android.PUA.General", "Emsisoft": "Android.Trojan.HiddenAds.QF (B)", "Comodo": "UnclassifiedMalware", "F-Secure": "", "DrWeb": "Android.Siggen.5746", "VIPRE": "", "TrendMicro": "ANDROIDOS_ZTORG.OPSUA", "McAfee-GW-Edition": "", "Sophos": "Andr/HiddnAd-D", "Cyren": "ZIP/Trojan.JLEG-6", "Jiangmin": "", "Webroot": "", "Avira": "ANDROID/Dropper.Agent.IZ.Gen", "Antiy-AVL": "Trojan/Android.Hiddad", "Kingsoft": "", "Microsoft": "Ransom:AndroidOS/LockScreen!rfn", "AegisLab": "", "ZoneAlarm": "HEUR:Trojan-Downloader.AndroidOS.Rootnik.g", "GData": "Android.Trojan.HiddenAds.QF", "AhnLab-V3": "Android-Trojan/Ztorg.53b44", "VBA32": "", "ALYac": "", "MAX": "malware (ai score=84)", "WhiteArmor": "Malware.HighConfidence", "Zoner": "", "Rising": "Dropper.Agent/Android!8.37E (cloud:ZDm0URi96CI)", "Yandex": "", "Ikarus": "Trojan-Dropper.AndroidOS.Agent", "Fortinet": "Android/Agent.ANY!tr", "AVG": "", "Panda": "", "Qihoo-360": "Other.Android.Gen"}], "permalink": "https://www.virustotal.com/file/5b9cf11bcace79ee7ea0f8adbe95a60655313e4530e83f0c1e4b36f2cb5589e6/analysis/", "result": 1}'`

**Comment by luckenzo** [comment]
Thanks! Adding the missing keys and values for each sample solved the problem. But I encountered other issues: 1) the output report contained less samples than the input report (2732 vs 3091). 2). Euphony appears not able to learn the pattern from some vendors. e.g., the following line in the VT report: `{"scan_id":"0d8645e25046b66799350b572d4c83a0fc63584794f00849aa7165e8af29cb25","sha256":"0d8645e25046b66799350b572d4c83a0fc63584794f00849aa7165e8af29cb25","resource":"0d8645e25046b66799350b572d4c83a0fc63584794f00849aa7165e8af29cb25","scan_date":"2017-12-12 17:18:50","positives":12,"total":63,"scans":{"CAT-QuickHeal":{"detected":true,"result":"Android.Smssend.Af612 (PUP)"},"Emsisoft":{"detected":true,"result":"Android.Riskware.SMSSend.gRQK (B)"},"Symantec":{"detected":true,"result":"Trojan.Gen.8!cloud"},"MAX":{"detected":true,"result":"malware (ai score=77)"},"McAfee":{"detected":true,"result":"Artemis!BA0224C044B0"},"BitDefender":{"detected":true,"result":"Android.Riskware.SMSSend.gRQK"},"TrendMicro-HouseCall":{"detected":true,"result":"Suspicious_GEN.F47V0912"},"Cyren":{"detected":true,"result":"ZIP/Trojan.DYKH-1"},"ClamAV":{"detected":true,"result":"Andr.Malware.Agent-1480723"},"GData":{"detected":true,"result":"Android.Riskware.SMSSend.gRQK"},"Arcabit":{"detected":true,"result":"Android.Riskware.SMSSend.gRQK"},"AegisLab":{"detected":true,"result":"Android.Riskware.Smssend!c"}}}` is represented as `"0d8645e25046b66799350b572d4c83a0fc63584794f00849aa7165e8af29cb25" : {
    "artemis" : 1
  },` in the output election.json file and is thus labeled as "artemis" as against "gRQK". 
Do you have any idea why these happens?

**Comment by fmind** [comment]
1) This happens when Euphony is not able to extract the family name from a vendor label. Some vendors use only the sha256 or the type of the malware as a label. Moreover, label such as "Trojan.Gen.8!cloud" do not have a clear family name as well.

2) There is many edge cases from VT reports. Is SMSSend a family name or a type ? Is gRQK a family name then ? or just some piece of information. The whole approach of Euphony is based on making "safe" prediction and improve incrementally on them. If gRQK is found to be a malware name in a clear-cut case, it will use this information and correctly classify this report as gRQK.

Note that you can always mention explicitly that gRQK is a malware family. You can find examples in resources/seeds.edn. You can update this file and use it as an input with `-s seeds-file.edn`. If you are confident that gRQK is a family name, pull requests are welcome :)

**Comment by luckenzo** [comment]
Thanks!
